### ISSUE TITLE
NullPointerException in PsiTreeAnyChangeAbstractAdapter

### ISSUE THREAD

**Issue by liebsterkamerad** [Flamenco/intellivue#10]
Intellij 2020.1: What other information should I provide? This NPE is coming from PsiTreeAnyChangeAbstractAdapter._childAdded_ and second one from _childRemoved_ 

`java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1541)
	at tv.twelvetone.intellij.plugins.tv.twelvetone.util.Debouncer.call(Debouncer.java:25)
	at tv.twelvetone.intellij.plugins.intellivue.VueModel$1.onChange(AnalyzeVueFile.kt:280)
	at com.intellij.psi.PsiTreeAnyChangeAbstractAdapter.childAdded(PsiTreeAnyChangeAbstractAdapter.java:27)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:376)
	at com.intellij.psi.impl.PsiManagerImpl.childAdded(PsiManagerImpl.java:262)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.lambda$fileCreated$0(PsiVFSListener.java:160)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:976)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.fileCreated(PsiVFSListener.java:146)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.fireForGrouped(PsiVFSListener.java:734)
	at one.util.streamex.CollapseSpliterator.accept(CollapseSpliterator.java:150)
	at one.util.streamex.CollapseSpliterator.forEachRemaining(CollapseSpliterator.java:140)
	at one.util.streamex.AbstractStreamEx.forEach(AbstractStreamEx.java:306)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.groupAndFire(PsiVFSListener.java:711)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.after(PsiVFSListener.java:700)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$1.after(PsiVFSListener.java:134)
	at jdk.internal.reflect.GeneratedMethodAccessor299.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:549)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:143)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:472)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:432)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:420)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:404)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:243)
	at com.sun.proxy.$Proxy146.after(Unknown Source)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvent(PersistentFSImpl.java:705)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.createChildFile(PersistentFSImpl.java:459)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.createChildData(VirtualFileSystemEntry.java:221)
	at org.jetbrains.vuejs.intentions.extractComponent.VueExtractComponentDataBuilder.createNewComponent(VueExtractComponentDataBuilder.kt:146)
	at org.jetbrains.vuejs.intentions.extractComponent.VueComponentInplaceIntroducer$performRefactoring$1$1.run(VueComponentInplaceIntroducer.kt:132)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:102)
	at org.jetbrains.vuejs.intentions.extractComponent.VueComponentInplaceIntroducer$performRefactoring$1.run(VueComponentInplaceIntroducer.kt:128)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:212)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at org.jetbrains.vuejs.intentions.extractComponent.VueComponentInplaceIntroducer.performRefactoring(VueComponentInplaceIntroducer.kt:125)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring$MyTemplateListener.templateFinished(InplaceRefactoring.java:948)
	at com.intellij.codeInsight.template.impl.TemplateState.fireTemplateFinished(TemplateState.java:1396)
	at com.intellij.codeInsight.template.impl.TemplateState.cleanupTemplateState(TemplateState.java:1105)
	at com.intellij.codeInsight.template.impl.TemplateState.finishTemplateEditing(TemplateState.java:1057)
	at com.intellij.codeInsight.template.impl.TemplateState.nextTab(TemplateState.java:939)
	at com.intellij.codeInsight.template.impl.actions.NextVariableAction$Handler.doExecute(NextVariableAction.java:44)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:216)
	at com.hasintech.intellij.angularTemplates.NextVariableHandler.doExecute(NextVariableHandler.java:55)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$null$2(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:103)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$3(EditorActionHandler.java:205)
	at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$runForEachCaret$3(CaretModelImpl.java:298)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:407)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:307)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:282)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:203)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:98)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:107)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:82)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:609)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:619)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:516)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:470)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:219)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:896)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by Flamenco** [comment]
@liebsterkamerad Any steps to reproduce this?

**Comment by Flamenco** [comment]
We added an NPE check and this should not be an issue again.
Fixed in v1.0.2

**Comment by Flamenco** [comment]
https://plugins.jetbrains.com/plugin/12014-intellivue/update/86297
